[csv.streamgage]
source = 'Postproc\Data\obsgage.csv'
idcol = 'MFName'
epsg = 4269
plotarg     = {markersize=20, color='k', alpha=1, zorder=61}
plotarg_loc = {marker="*", markersize=50, color='r', alpha=1, zorder=62, linewidth=1.2}
writeshp = true

[tseries.obsflow]
source = 'Postproc\Data\obsflow.csv'
mintime = 2003-10-01
maxtime = 2023-10-01
idcol = 'MFName'
valcol = 'obscfs'
rename = {columns={obscfs='Observed'}}
plotarg = {linewidth=1.0, color='black', zorder=2}
location = {csv='streamgage'}
legend = true

[tseries.obsflow_vol]
parent = "obsflow"
rate_to_cumvol = true
a_scale = 1.9834710743801653   # 1 cfs*day to AF/month


[tseries.obsflow_calib]
parent = "obsflow"
mintime = 2017-10-01

[tseries.obsflow_vol_calib]
parent = "obsflow_vol"
mintime = 2017-10-01

[tseries.obsprleak_pst]
source = 'Postproc\Data\20250508_pecosleak.csv'
idcol = 'MFName'
valcol = 'obsname'
plotarg = {linewidth=0.5, marker='.', color='black', zorder=2}
legend = true

[tseries.obsflow_pst]
parent = "obsflow"
idcol = 'MFName'
valcol = 'obsname'