[csv.obswells] #specify csv containing xy data for mapping
source = 'Postproc\Data\obswell_full.csv'
idcol = 'wellname'
filter = "active == 1"
plotarg     = {markersize=10, color='k', alpha=1, zorder=60}
plotarg_loc = {markersize=25, facecolor='k', edgecolor='r', alpha=1, zorder=61, linewidth=1.2}


[tseries.obsgwlevel] #SPECIFY CSV WITH COMPILED WELL OBSERVATION DATA
source = 'Postproc\Data\obsgwl.csv'
idcol = 'wellname'
valcol = 'obsgwl'
mintime = 2003-10-01
maxtime = 2023-10-01
plotarg = {linewidth=0.5, marker='.', color='black', zorder=2}
location = {csv='obswells'}
#mintime = 1940-01-01
legend = true


[tseries.obsgwlevel_calib] #SPECIFY CSV WITH COMPILED WELL OBSERVATION DATA
parent = 'obsgwlevel'
mintime = 2017-10-01

[tseries.obsgwlevel_pst]
parent = 'obsgwlevel'
valcol = 'obsname'

[tseries.obsgwlevel_pst_calib]
parent = 'obsgwlevel_pst'
mintime = 2017-10-01
