include = ['Postproc\TOML\simhead.toml','Postproc\TOML\simflow.toml','Postproc\TOML\obsflow.toml']

[scatterplot.gwlevel]
plotdata = [{hobout='simgwlevel'}]
xcol = 'Observed'
histogram = true
stats = true
regression_line = true
exttable = {csv='obswells'}
xlabel = 'Observed groundwater elevation (feet)'
ylabel = 'Simulated groundwater elevation (feet)'
xlim = [-150, 550]
ylim = [-150, 550]
plotarg = {s=4, alpha=1.0}
legend=true
legendarg={ncols=5}
text = [{x=-0.13, y=-0.1, text=" ", alpha=0.5}, {x=1.0, y=1.1, text=" ", alpha=0.5}]
logo = {source='Postproc\Data\ss-papadopulos-and-associates-logo.png', alpha=0.8}



[pdf.plotScatterplotHead]
figsize = [8, 8]
pages = {scatterplot=['gwlevel']}




#################################################


[scatterplot.Streamflow]
plotdata = [{tseries='obsflow'}, {tseries='simflow'}]
xcol = 'Observed'
grouping = 'MFName'
histogram = true
stats = true
regression_line = true
xlabel = 'Observed Streamflow (cfs)'
ylabel = 'Simulated Streamflow (cfs)'
xlim = [0, 4000]
ylim = [0, 4000]
legend=true
text = [{x=-0.13, y=-0.1, text=" ", alpha=0.5}, {x=1.0, y=1.1, text=" ", alpha=0.5}]
logo = {source='Postproc\Data\ss-papadopulos-and-associates-logo.png', alpha=0.8}



[scatterplot.Streamflow_Log]
plotdata = [{tseries='obsflow'}, {tseries='simflow'}]
xcol = 'Observed'
grouping = 'MFName'
histogram = true
stats = true
regression_line = true
xlabel = 'Observed Streamflow (cfs)'
ylabel = 'Simulated Streamflow (cfs)'
xlim = [0.1, 5000]
ylim = [0.1, 5000]
xscale = "log"
yscale = "log"
legend=true
text = [{x=-0.13, y=-0.1, text=" ", alpha=0.5}, {x=1.0, y=1.1, text=" ", alpha=0.5}]
logo = {source='Postproc\Data\ss-papadopulos-and-associates-logo.png', alpha=0.8}

[pdf.plotScatterplotFlow]
figsize = [8, 8]
pages = {scatterplot=["Streamflow", 'Streamflow_Log']}
