include = ['Postproc\TOML\global.toml',
           'Postproc\TOML\basemap.toml',
]

[mapplot.AllLayers]
parent = 'basemap'
# text = {x=0.05,y=0.95,text="All Layers",va="top",ha="left",fontsize="large"}
plotdata2 = {csv='meanerr'}
logo = {source='Postproc\Data\ss-papadopulos-and-associates-logo.png', alpha=0.8}

[csv.meanerr]
source = 'headerr.csv'
idcol = 'wellname'
size  = 'rmse'
sizescale = 10
plotarg     = {column='merr', edgecolor='k', vmin=-60, vmax=60, cmap='RdBu_r,12', legend=true, legend_kwds={shrink=2.0, fraction=0.03, pad=0.01, label='Mean residual (feet)'}, zorder=60}

[pdf.plotHeadErrMap]
pages = {mapplot=['AllLayers']}

